//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuyaTabir.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUYA
    {
        public int RuyaID { get; set; }
        public string Ruya1 { get; set; }
        public string RuyaTabir { get; set; }
    }
}
